version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - IncPlusPlus
  assignees:
  - IncPlusPlus
  ignore:
  - dependency-name: com.google.guava:guava
    versions:
    - ">= 29.0-jre.a, < 29.1"
  - dependency-name: org.assertj:assertj-core
    versions:
    - ">= 3.16.a, < 3.17"
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-starter-actuator
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-starter-security
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework.boot:spring-boot-test
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: org.springframework:spring-test
    versions:
    - ">= 5.2.a, < 5.3"
