dist: xenial
language: java
jdk:
  - openjdk14
cache:
  directories:
    - $HOME/.m2
# See https://github.com/travis-ci/travis-ci/issues/8667
install: true
before_script:
  - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh
    | sudo bash'
script:
  - mvn clean jacoco:prepare-agent install jacoco:report
  - fossa init
  - fossa analyze
after_success:
  - bash <(curl -s https://codecov.io/bash)