dist: xenial
language: java
cache:
  directories:
    - $HOME/.m2
services:
  - mongodb
matrix:
  include:
    - jdk: oraclejdk11
      script: mvn clean install
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - jdk: openjdk11
      script: mvn clean install