dist: xenial
language: java
jdk:
  - oraclejdk11
  - openjdk11
cache:
  directories:
    - $HOME/.m2
services:
  - mongodb
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)