dist: xenial
language: java
jdk:
  - openjdk14
cache:
  directories:
    - $HOME/.m2
# See https://github.com/travis-ci/travis-ci/issues/8667
install: true
before_script:
  - 'curl -H ''Cache-Control: no-cache'' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh
    | sudo bash'
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - mvn clean jacoco:prepare-agent install jacoco:report
  - fossa init
  - fossa analyze
after_success:
  - "./cc-test-reporter format-coverage -t jacoco ./target/jacoco_fixed_for_codeclimate.xml"
  - "./cc-test-reporter upload-coverage"
  - bash <(curl -s https://codecov.io/bash)